name: documentation
on:
  push:
    branches: devel
  workflow_dispatch:

jobs:

  # There is no way as of now to move artifacts around jobs and
  # across workflows. So we build the Python bindings here too.
  build:
    runs-on: ubuntu-20.04
    steps:

      # Build manifpy

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup apt
        run: |
          sudo apt update
          sudo apt install -y libeigen3-dev
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          pip install pytest "pybind11[global]"
          pip install -r requirements.txt
      - name: Build
        run: pip install .

  # build:
  #   runs-on: ubuntu-20.04
  #   needs: [pybind11]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2

      # Build documentation website

      - name: Fetch apt deps
        run: |
          sudo apt update
          sudo apt install -y libeigen3-dev flex bison doxygen graphicsmagick-imagemagick-compat
      - name: Fetch Python deps
        run: python -m pip install jinja2 Pygments
      - name: Fetch m.css
        working-directory: ${{runner.workspace}}
        run: git clone git://github.com/mosra/m.css

      - name: Build Python docs
        run: python3 ${{runner.workspace}}/m.css/documentation/python.py conf_python.py
      - name: Build C++ docs
        run: python3 ${{runner.workspace}}/m.css/documentation/doxygen.py Doxyfile-mcss
      - name: Build site
        run: python3 ${{runner.workspace}}/m.css/documentation/doxygen.py conf.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: docs/site

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/site